# Generated by Django 5.0.6 on 2025-05-30 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_song_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=2, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
