# Generated by Django 5.2 on 2025-06-01 17:58

import music_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_song_favorites_alter_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(help_text='Upload an audio file (MP3, WAV, OGG, or M4A)', upload_to='songs/', validators=[music_app.models.validate_audio_file]),
        ),
    ]
